/**
 * Import IBTrACS North Indian Ocean best tracks into `besttrack_points`.
 *
 * Usage:
 *   node scripts/import_ibtracs.js [path/to/ibtracs.NI.list.v04r01.csv] [--since 1980]
 * Default path: ../data/static/ibtracs.NI.list.v04r01.csv
 * Idempotent (upsert on (sid, iso_time)); safe to re-run after refreshing the CSV.
 * Also stores JTWC wind radii per quadrant (USA_R34/R50/R64_*, nautical miles), RMW, ROCI and storm
 * motion (migration 008), and writes data/wind_radii_climatology.json: median radii by intensity,
 * used for storms without measured radii (live systems, pre-2001 storms).
 * Grade/wind/pressure prefer the RSMC New Delhi (IMD) values, then WMO.
 */

require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { pool } = require('../src/db/connection');

const RADII = ['r34_ne', 'r34_se', 'r34_sw', 'r34_nw', 'r50_ne', 'r50_se', 'r50_sw', 'r50_nw',
  'r64_ne', 'r64_se', 'r64_sw', 'r64_nw'];
const int = v => (v === '' || v == null ? null : Math.round(parseFloat(v)));

// Median quadrant-mean radius (nm) of each wind threshold, per 10 kt intensity bin (JTWC 1-min winds)
const bins = {};
function collectClimatology(kt, radii) {
  if (kt == null || radii[0] == null) return;
  const b = Math.floor(kt / 10) * 10;
  bins[b] = bins[b] || { r34: [], r50: [], r64: [] };
  for (const [k, i] of [['r34', 0], ['r50', 4], ['r64', 8]]) {
    const q = radii.slice(i, i + 4);
    if (q.every(v => v != null)) bins[b][k].push(q.reduce((a, v) => a + v, 0) / 4);
  }
}
function writeClimatology() {
  const med = a => (a.length ? [...a].sort((x, y) => x - y)[Math.floor(a.length / 2)] : 0);
  const table = Object.fromEntries(Object.entries(bins).map(([b, v]) => [b, {
    r34_nm: Math.round(med(v.r34)), r50_nm: Math.round(med(v.r50)), r64_nm: Math.round(med(v.r64)), n: v.r34.length,
  }]));
  fs.writeFileSync(path.join(__dirname, '..', 'data', 'wind_radii_climatology.json'), JSON.stringify({
    note: 'Median quadrant-mean JTWC wind radii (nautical miles) by 10 kt intensity bin, North Indian Ocean '
      + 'IBTrACS v04r01; 0 = threshold not reached. Generated by scripts/import_ibtracs.js.',
    bins: table,
  }, null, 1));
}

async function main() {
  const args = process.argv.slice(2);
  const sinceIdx = args.indexOf('--since');
  const since = sinceIdx >= 0 ? parseInt(args[sinceIdx + 1], 10) : 1980;
  const file = args.find((a, i) => !a.startsWith('--') && args[i - 1] !== '--since')
    || path.join(__dirname, '..', '..', 'data', 'static', 'ibtracs.NI.list.v04r01.csv');

  const rl = readline.createInterface({ input: fs.createReadStream(file), crlfDelay: Infinity });
  let cols = null;
  let lineNo = 0;
  let batch = [];
  let total = 0;

  const flush = async () => {
    if (!batch.length) return;
    const [res] = await pool.query(
      `INSERT INTO besttrack_points
         (sid, season, name, subbasin, iso_time, latitude, longitude, grade, wind_kt, pressure_hpa, dist2land_km,
          ${RADII.join(', ')}, rmw_nm, roci_nm, storm_speed_kt, storm_dir_deg)
       VALUES ?
       ON DUPLICATE KEY UPDATE ${[...RADII, 'rmw_nm', 'roci_nm', 'storm_speed_kt', 'storm_dir_deg']
    .map(c => `${c} = VALUES(${c})`).join(', ')}`, [batch]);
    total += res.affectedRows;
    batch = [];
  };

  for await (const line of rl) {
    lineNo++;
    if (lineNo === 1) { cols = line.split(','); continue; }
    if (lineNo === 2) continue; // units row
    const f = line.split(',');
    const get = name => f[cols.indexOf(name)]?.trim() ?? '';
    const season = parseInt(get('SEASON'), 10);
    if (!(season >= since)) continue;
    const num = v => (v === '' ? null : parseFloat(v));
    const name = get('NAME');
    batch.push([
      get('SID'), season, name === 'NOT_NAMED' || name === 'UNNAMED' ? null : name, get('SUBBASIN') || null,
      get('ISO_TIME'), num(get('LAT')), num(get('LON')), get('NEWDELHI_GRADE') || null,
      num(get('NEWDELHI_WIND')) ?? num(get('WMO_WIND')), num(get('NEWDELHI_PRES')) ?? num(get('WMO_PRES')),
      num(get('DIST2LAND')),
      ...RADII.map(c => int(get(`USA_${c.toUpperCase()}`))), int(get('USA_RMW')), int(get('USA_ROCI')),
      num(get('STORM_SPEED')), num(get('STORM_DIR')),
    ]);
    collectClimatology(num(get('USA_WIND')), RADII.map(c => int(get(`USA_${c.toUpperCase()}`))));
    if (batch.length >= 1000) await flush();
  }
  await flush();
  writeClimatology();
  console.log(`Imported ${total} new best-track points (seasons >= ${since}) from ${file}`);
  await pool.end();
}

main().catch(err => {
  console.error('Import failed:', err.message);
  process.exit(1);
});
